### ISSUE TITLE
Display Link is not working

### ISSUE THREAD

**Issue by Littletitus** [grafmar/Arduino-Reflow-Oven#6]
The used link to the display is not working! I do have a Display here which looks like in the frizzing pic, but not sure if it’s the right one as the pins used for the temperature sensor are also used for an SD-card reader at the display! Uploaded the code, but only do get a white display without any text / infos…

**Comment by grafmar** [comment]
Hi,
If you know which display driver chip you have you might adapt it.
please try to set the other driver in ReflowOven.h:

// Define the hardware: Original(ST7781 TFT) / my setup (SPFD5408 TFT)
#define USE_ST7781
//#define USE_SPFD5408

Otherwise you can replace the tft object in display.cpp with the one of your display driver:
// define the tft-object with the right library
#ifdef USE_ST7781
SWTFT tft;
#elif defined(USE_SPFD5408)
TftSpfd5408 tft(LCD_CS, LCD_CD, LCD_WR, LCD_RD, LCD_RESET);
#endif // USE_ST7781

**Comment by grafmar** [comment]
Changed the link to a search link and added instructions to tweak the code. The search on aliexpress is not always working, but at least it is a hint.
